### ISSUE TITLE
BUG: Fix card height resizing differently

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/hacktoberfest-website-2019#17]
- [x] Home Page
- [x] Projects Page

![Screenshot from 2019-10-06 16-36-29](https://user-images.githubusercontent.com/34790378/66268109-a6d0a080-e857-11e9-8258-82166db43056.png)

![Screenshot from 2019-10-06 16-38-25](https://user-images.githubusercontent.com/34790378/66268118-bc45ca80-e857-11e9-90ce-4dfdb881c364.png)

## Possible Fix:
slice description to a minimum number of words before rendering

**Comment by ykatiyar** [comment]
i would like to work on this issue

**Comment by abhijithvijayan** [comment]
@NuCelyA Sure.

**Comment by ykatiyar** [comment]
since i'm new to open dev, i m having some confusion in setting up this project 
can u plz help tell what values or changes are to be done in .env files

**Comment by abhijithvijayan** [comment]
@NuCelyA

Create a GitHub token with repo scope.

Create a `variables.env` file under `server/` with contents from `.sample` file and update apikey

Run `yarn run server`

And in another terminal `yarn run dev:web`

**Comment by abhijithvijayan** [comment]
@NuCelyA Any luck on this?

**Comment by ykatiyar** [comment]
i m stuck in setting this up
i m able to load whole page but project is not being loaded 

> Failed to load resource: the server responded with a status of 500 (Internal Server Error)

this error is shown by chrome console

**Comment by abhijithvijayan** [comment]
@NuCelyA Are you sure you updated `GITHUB_TOKEN="YOUR-GITHUB-TOKEN"` entry in `variables.env` file you created under `server/` and your express server is running with `yarn run server` in other terminal window?

**Comment by ykatiyar** [comment]
yes i have updated that
do i have to do some change in .env file under client folder or 
assign value to NODE_ENV in variables.env under server

**Comment by abhijithvijayan** [comment]
@NuCelyA set `NODE_ENV` to `development`

**Comment by abhijithvijayan** [comment]
@NuCelyA Are you having trouble again? Do you want me to assign this to someone else?
