### ISSUE TITLE
Update footer link to repo link

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/hacktoberfest-website-2019#19]
Add an entry `repoLink` to https://github.com/ceadoor/hacktoberfest-website-2019/blob/master/client/src/config/index.js

And use this entry instead of `githubLink` in Footer link

**Comment by iam-abbas** [comment]
may i work on this?

**Comment by abhijithvijayan** [comment]
@iam-abbas sure. Copy url of this repo.

**Comment by abhijithvijayan** [comment]
#25
