### ISSUE TITLE
start fetching from 2nd page to avoid redundancy

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/hacktoberfest-website-2019#23]
As home page already fetches page: 1 data, it seems better to start fetching from 2nd page onwards.

### Possible Fix
Update this line
https://github.com/ceadoor/hacktoberfest-website-2019/blob/b4565034acfbf96f2732a5b7383dbebf3a69b636/client/src/components/Projects/Projects.js#L103

to `page: 2`

And update this link
https://github.com/ceadoor/hacktoberfest-website-2019/blob/b4565034acfbf96f2732a5b7383dbebf3a69b636/client/src/components/Projects/Projects.js#L110

to `this.fetchRepos({ page: this.state.page });`

**Comment by digikin** [comment]
can I try

**Comment by abhijithvijayan** [comment]
@digikin Assigned. Shoot up a PR when it's done.
