### ISSUE TITLE
position userImage to center in progress page

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/hacktoberfest-website-2019#28]
![Screenshot from 2019-10-06 22-06-30](https://user-images.githubusercontent.com/34790378/66272308-b36bed80-e885-11e9-8a71-dae672bfaf16.png)

Screenshot shows image being left located in hexagon

**Comment by donycisne** [comment]
Can I be assigned to this?

**Comment by abhijithvijayan** [comment]
@donycisneros Have at it. Shoot up PR afterwards.

**Comment by abhijithvijayan** [comment]
#32
