### ISSUE TITLE
add validation to request body

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/hacktoberfest-website-2019#3]
use `express-validator` to validate the body content for the route

Sample validation criterias and controller is already present in `validateBodyController` file

Validate `username` field

**Comment by praveen-me** [comment]
Hi @abhijithvijayan, I would like to work on this issue.
How does it sound to you?

**Comment by abhijithvijayan** [comment]
@praveen-me sorry for the late response.

Someone has already done a PR for this issue.
